from django.conf.urls import include, patterns, url
from backoffice.api import views

urlpatterns = patterns('',
    url(r'^get_user_schoolclasses/$', views.get_user_schoolclasses, name='api_get_user_schoolclasses'),
    url(r'^delete_school_class/$', views.delete_school_class, name='api_delete_school_class'),
    url(r'^get_all_classes_students/$', views.get_all_classes_students, name='api_get_all_classes_students'),
    url(r'^delete_user/$', views.delete_user, name='api_delete_user'),
    url(r'^get_schoolclass_administrators/(?P<class_id>\d+)/$', views.get_schoolclass_administrators, name="api_get_schoolclass_administrators"),
    url(r'^remove_administrator/$', views.remove_administrator, name="api_remove_administrator"),
    url(r'^add_administrator/$', views.add_administrator, name="api_add_administrator"),
    url(r'^get_statistics/', include(patterns('',
        url(r'^(?P<class_id>\d+)/(?P<student_id>-?\d+)/$', views.get_statistics, name='api_get_statistics'),
        url(r'^(?P<ref>[\w-]+)/(?P<student_id>\d+)/$', views.get_exercise_statistics, name='api_get_exercise_statistics'),
    ))),
    url(r'^get_subjects/$', views.get_subjects, name="api_get_subjects"),
    url(r'^get_exercises/$', views.get_exercises, name="api_get_exercises"),
    url(r'^get_subjects_exercices/$', views.get_subjects_exercices, name="api_get_subjects_exercices"),
    url(r'^save_subject_config/', include(patterns('',
        url(r'^$', views.save_subject_config, name="api_save_subject_config"),
        url(r'^(?P<subject_config_id>\d+)/$', views.save_subject_config, name="api_update_subject_config"),
    ))),
    url(r'^save_exercise_config/', include(patterns('',
        url(r'^$', views.save_exercise_config, name="api_save_exercise_config"),
        url(r'^(?P<exercise_config_id>\d+)/$', views.save_exercise_config, name="api_update_exercise_config"),
    ))),
    url(r'^get_configurations/$', views.get_configurations, name="api_get_configurations"),
    url(r'^delete_exercise_configuration/$', views.delete_exercise_configuration, name="api_delete_exercise_configuration"),
    url(r'^delete_subject_configuration/$', views.delete_subject_configuration, name="api_delete_subject_configuration"),
)
